name: nihongo_no_sensei
description: An Unofficial Android app for the website https://nihongonosensei.net/
version: 1.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^2.1.1
  url_launcher: ^5.0.2
  http: ^0.12.0+2
  html: ^0.14.0+2
  sprintf: ^4.0.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_html: ^0.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true